### ISSUE TITLE
Many errors and forks on mainnet 2.4.2

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#273] opened 2019-11-18 11:43 UTC
See logs on your node 2.4.2

![image](https://user-images.githubusercontent.com/5445357/69049711-14651480-0a33-11ea-8f82-189ee0930edf.png)

**Comment by harry1453** [comment] 2019-11-23 12:08
The log says there is an error reading the h2 database file...

**Comment by llybin** [comment] 2019-11-23 12:32
Yes, we see errors from other nodes. And I noticed increasing forks, may be add some pre validation... I saw something in 3.0 may be it solved this problem

**Comment by harry1453** [comment] 2019-11-23 12:57
I've had someone else report this in 3.0.0-alpha2, will see if I get a log from them

**Comment by matbogdan79** [comment] 2020-01-17 10:53
I get the same kind of errors on mariadb too.
https://cdn.discordapp.com/attachments/658988444583854080/667672279311974420/unknown.png

**Comment by harry1453** [comment] 2020-01-18 15:20
These errors are all P2P errors, nothing to worry about, caused by network connectivity issues. These kind of errors will be hidden from V3 onwards

**Comment by llybin** [comment] 2020-02-08 18:46
on 3.0.0 https://github.com/burst-apps-team/burstcoin/commit/4b1a2608621ae50cc70c4ad3321f8a12ed6f036c I get errors, maybe hide these messages

`[WARNING] 2020-02-09 01:45:34 brs.peer.HttpPeerImpl - Error exchanging info with peer
java.lang.IllegalStateException: Returned JSON was null
        at brs.peer.HttpPeerImpl.exchangeInfo(HttpPeerImpl.kt:195)
        at brs.peer.HttpPeerImpl.connect(HttpPeerImpl.kt:373)
        at brs.services.impl.PeerServiceImpl$peerConnectingThread$1.invoke(PeerServiceImpl.kt:348)
        at brs.services.impl.PeerServiceImpl$peerConnectingThread$1.invoke(PeerServiceImpl.kt:47)
        at brs.services.impl.RxJavaTaskSchedulerService$repeatingTaskToTask$$inlined$safeCreateCompletable$1.subscribe(RxJavaTaskSchedulerService.kt:177)
        at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by llybin** [comment] 2020-02-08 19:58
I tested the last dev version with sqlite on testnet, full log: https://yadi.sk/d/svC3vQpOb0xgMg

**Comment by jjos2372** [comment] 2020-12-31 21:14
Closing, looks like to be an issue with 2.4.X

**Closed by jjos2372** 2020-12-31 21:14 UTC
