### ISSUE TITLE
Strange unconfirmed transactions

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#166] opened 2019-06-08 22:49 UTC
API return unconfirmed transactions but looks like they are confirmed already.

BRS API unconfirmed transactions in this list:

![Screenshot_2019-06-09-05-33-45-514_com android chrome](https://user-images.githubusercontent.com/5445357/59152929-bc37e880-8a78-11e9-8d31-f5e3c54c489b.png)

First from list above:

![Screenshot_2019-06-09-05-33-27-419_com android chrome](https://user-images.githubusercontent.com/5445357/59152927-b2ae8080-8a78-11e9-9727-39626ec6cc1d.png)

The last from list:

![Screenshot_2019-06-09-05-35-55-076_com android chrome](https://user-images.githubusercontent.com/5445357/59152931-c35ef680-8a78-11e9-899f-0cb183674325.png)

Also, I've seen unconfirmed 23(!?) hours ago and 32 seconds ago, which gone later. List is not stuck fully.

At this moment can see on https://wallet.burst.devtrue.net

``` json
{"unconfirmedTransactions":[{"type":0,"subtype":0,"timestamp":152299142,"deadline":1000,"senderPublicKey":"da5920b7e444d916eff561c46348fdf03d80400c45dc57eb35b66dde3916fe06","recipient":"4898858706632937917","recipientRS":"BURST-Z6FX-39CU-DR7L-6Y3Z9","amountNQT":"5000000","feeNQT":"735000","signature":"3c071d6d5b2aca4821b05bee950ed3109f57860f638c56edfbdf99f3b6f2bf077fc644a4f86961b0b18e3dff20b33a8ad7e0c226625061595e4580b89c55c477","signatureHash":"c352499f85eb4aa9d2c5a7331929b742541f859e4ee6296934bb84d1571b5e07","fullHash":"ab2902cea172000bce248c77a5a59da3a244e92f155567bed7d93be8f299bb08","transaction":"792759573688756651","sender":"16849287556676766732","senderRS":"BURST-3M2E-SDR4-JSKY-GK7PM","height":629687,"version":1,"ecBlockId":"13959260229846968143","ecBlockHeight":629673},{"type":0,"subtype":1,"timestamp":152299595,"deadline":1440,"senderPublicKey":"b3295ef28034d5a5150974dd23323ee135f8d74069c19da479379a27c0e6cc5b","amountNQT":"19059001850","feeNQT":"2205000","signature":"57523b757dd398ce7872d88e8d494997e464d2ad2cf41a3c13408aec0bfd6409a25c4bed7c256069cc83e269b2643cc62a373f9985461bd42204b70bc2faa6f0","signatureHash":"8cba8aec127e4ff776e0e500895e4d3cb37641f9133fc15e82bfef8110df7bb5","fullHash":"45ee282f3b1d9b05e8651d790469441b887c22fd7824efe6b0464a69661b2aac","transaction":"403948731611278917","attachment":{"version.MultiOutCreation":1,"recipients":[["14298473703018581232","230635262"],["15835762590554835412","244533704"],["15880068665947308368","121464352"],["2861053951274811221","706550022"],["7255227437038889586","1492783109"],["10119937713144793572","978582374"],["10517267321639061650","344607752"],["558316898251885051","136800933"],["4279780136039435112","1064866533"],["8055702773720532633","185867534"],["9293483248336378091","1181787209"],["15315842440479395429","145984472"],["678269846049583981","201774874"],["728911464067386037","136477270"],["7218925791556203938","105115075"],["14076490857905988952","380635600"],["2102122662740992161","201204225"],["5190144021270291312","140044774"],["9244105500500381800","380727339"],["16373922841271338669","243115576"],["14080054006184875111","807867589"],["478048529689595114","1440086771"],["4783791696038114455","103911580"],["9349828117993348648","279873155"],["10817003053507755972","263822452"],["9741442799084564119","106899380"],["12753280106257581144","688103110"],["12867003203108114366","114949521"],["14653230141344995543","776985272"],["5046839534036673199","423686548"],["5591219772764086745","102583783"],["8688737834781935399","200115029"],["9260630353859441411","104221452"],["16026549622344642756","399252378"],["16320149368046575963","121367002"],["17333372594426509125","158961290"],["17508987893555845794","705857810"],["528108613926029500","1283534386"],["1238560784044299720","191039203"],["3914646458532816283","101281626"],["11282319608315185116","881764800"],["12728010012452727904","231364131"],["15651825346939360574","293590046"],["18183109408831014011","145158404"],["48989701784634870","100962866"],["427290848471141115","128482152"],["4990567746885034653","156897840"],["10878528575941276804","122824285"]]},"sender":"357805355326612814","senderRS":"BURST-MBCG-4ERH-FVH5-2GTXB","height":629687,"version":1,"ecBlockId":"17180587905509429047","ecBlockHeight":629676},{"type":0,"subtype":1,"timestamp":152311592,"deadline":1440,"senderPublicKey":"b3295ef28034d5a5150974dd23323ee135f8d74069c19da479379a27c0e6cc5b","amountNQT":"19697909582","feeNQT":"2205000","signature":"d4ca87888436de798e72aac7cef7f29b58368357208a41331e9c1be7e11416097246f7923b8a3c2327d46b50803aeeb14c7bb42dc13997b2b7879ef9e52ca840","signatureHash":"7c331c99e398e8aaf69fc5a99c289999fa4edfbb2e114ec611871f3a4a723e6b","fullHash":"02b8e67f98d7ceb544c20b0d290b2997476f69eef25f4c4e48aca61333eda34a","transaction":"13100645416048179202","attachment":{"version.MultiOutCreation":1,"recipients":[["1460037974540257564","952040606"],["12563332802610942475","4508103032"],["13601044406284485081","7708093407"],["17203836851449535296","963353843"],["1365297522942717064","5566318694"]]},"sender":"357805355326612814","senderRS":"BURST-MBCG-4ERH-FVH5-2GTXB","height":629738,"version":1,"ecBlockId":"7574529478741790406","ecBlockHeight":629730},{"type":1,"subtype":5,"timestamp":152295753,"deadline":1440,"senderPublicKey":"e8a39b2330e978240a77bc48ccecf9b584aba4f89f3fbd950fde997682e84b32","amountNQT":"0","feeNQT":"6615000","signature":"57073e0a466b34286b74161d0d90a37314666cbdd6df41550064c2d67a3e0f002029b81179708f67f25fc6b161ce4a8bce0d9283af1c4804c36f8fb3a291f58c","signatureHash":"7ea481c2de6405d09a833e169e0e622c0312f73eaed7afa1ecb014629239284f","fullHash":"8236feaf273dfae87869427538f8a1a613676267ca41488a9b27463410d01a80","transaction":"16787797801642636930","attachment":{"version.AccountInfo":1,"name":"PhilD","description":""},"sender":"17270042119929870970","senderRS":"BURST-AGMU-TUV9-8L9N-G5WCZ","height":629671,"version":1,"ecBlockId":"3779229800182102245","ecBlockHeight":629663},{"type":0,"subtype":1,"timestamp":152299771,"deadline":1440,"senderPublicKey":"25cc2bb30ee7665737c9721090313c85176e485cd9a15495a0f3abc359d8d632","amountNQT":"188446543372","feeNQT":"10000000","signature":"8598af09544c9f0f06c37b588a452527e99ce42e696a8c4d1c29b72841365604e0e26193aeb8d9c48d14358f69791878c6ed9ecf89477187d17b1120dd087d0e","signatureHash":"b6faac990c78d670f655972cd32bff4fd895188d76b70232aa2e4bba385afae0","fullHash":"d7aa9fcb8089a03763e65875f920e4cd9a0a8d3b989498618e37ba0fcb8723ee","transaction":"4008354854624799447","attachment":{"version.MultiOutCreation":1,"recipients":[["13357646821867656182","10000214512"],["14648544394362136112","10005389512"],["15201317521133864651","10159197177"],["17290940933204112031","13217309353"],["6861725287676781565","10010598110"],["7828229672720219380","10050374849"],["12140740123223557265","10108350938"],["9763878029668769612","10253336364"],["13750024092017113601","62565553484"],["18440282157318988712","10063228301"],["997887209061908662","10013952939"],["4015470661501094160","10182647379"],["5691458095854048877","11816390454"]]},"sender":"888561138747819634","senderRS":"BURST-HKML-NRG6-VBRA-2F8PS","height":629687,"version":1,"ecBlockId":"17180587905509429047","ecBlockHeight":629676},{"type":0,"subtype":0,"timestamp":152295829,"deadline":1440,"senderPublicKey":"94c851b11867693be791b234af4fc7ba2e231cf75549e3a2df9df19cf738e057","recipient":"16754918265897606532","recipientRS":"BURST-HRE6-EJVS-75KV-GFD3K","amountNQT":"50806643975","feeNQT":"100000000","signature":"cb59e1fd8ec17651ce01eb323b00fe48e8f7811e4bb5b2e45ac22f22d9e29d04ed69eff6df31e9dac248fcb0b5e962741c66b19570672f1c1a5be833d77f6b3d","signatureHash":"b72aa5683a77c612a17f49a353139c3b8a3590f000f772eeac0274b8835d0d30","fullHash":"3cafd2eda31c60db6f38fbfbe323e384f612c89e1c925fdf917c7f25ab24b2c0","transaction":"15807666182465695548","sender":"17939161211692180466","senderRS":"BURST-3SZL-4G5Q-NFTM-HN7XK","height":629671,"version":1,"ecBlockId":"3779229800182102245","ecBlockHeight":629663},{"type":0,"subtype":0,"timestamp":152295671,"deadline":900,"senderPublicKey":"bf33c5faeb0c19ae167dac120b9f871d362b3a951e7d20f1254ff83b5b265407","recipient":"17267540548048980516","recipientRS":"BURST-U4K6-NJHK-MEGJ-G2PAZ","amountNQT":"2414170450903","feeNQT":"100000000","signature":"1295cae65f41ef86a5f2dd8e76ef65f59a618605f0d50e066a9ca6b31055720d635177afe66ac2b35f50a841716cdeab7f9cc91c06a53208dcb51c7918bc4fe8","signatureHash":"1b8236e8a422b5a9caa1edb1f8198185ba25413e35b077907978c5d2b0fa7acd","fullHash":"0e6d74f894fb83043c7709c02b3cbab3c3943fe02cc3fe651fb355f85e75f47f","transaction":"325380215342918926","sender":"5810532812037266198","senderRS":"BURST-R8SQ-TUEM-DTHQ-7ATA3","height":629671,"version":1,"ecBlockId":"3779229800182102245","ecBlockHeight":629663},{"type":0,"subtype":0,"timestamp":152295656,"deadline":900,"senderPublicKey":"bf33c5faeb0c19ae167dac120b9f871d362b3a951e7d20f1254ff83b5b265407","recipient":"6276791127825888006","recipientRS":"BURST-7ES8-ATHQ-N7MD-76X8G","amountNQT":"900000000","feeNQT":"100000000","signature":"e6476196d3ec317abf1f03bc8442fd5a1a2a88ee8a0aa6d1553eb0095e97090e2e0eeab70f23843f6790aa462569e2183382665230c99333572ee6b6b0a54fc5","signatureHash":"9813620cadfe69e5ba2e6cb080a224d6622a6d37168c4036f9fa653ec1cb9673","fullHash":"6b1911e69df34713b6376f74af34234aa39d06929212eee1d123a7a130c49e49","transaction":"1389346869562382699","sender":"5810532812037266198","senderRS":"BURST-R8SQ-TUEM-DTHQ-7ATA3","height":629671,"version":1,"ecBlockId":"3779229800182102245","ecBlockHeight":629663},{"type":0,"subtype":0,"timestamp":152299501,"deadline":1440,"senderPublicKey":"d21c6c25feb45a73e35cebb9eab27aac204458e9bb515fbd25abd1ad4fb77618","recipient":"14714824533976319930","recipientRS":"BURST-T3XU-YFZX-VXF4-EGEFS","amountNQT":"12003985642","feeNQT":"100000000","signature":"f29871960e7b7136ce230385d457e94718c48ad8781e69b5b5fa05b44dc75d0ec99649289c304407488bdb36bceeef8cbe0fa57e779a95da13655351711270de","signatureHash":"a08c8013de36832c5912ed6c7234783437fcf31cdc0947b1e40c346c23b14938","fullHash":"c6002c6db7b4ee9f88a8fe6aef6e291914e173dc2d2bac436ff5e3530fee5246","transaction":"11524347196391293126","sender":"11084303456378837181","senderRS":"BURST-JQ7X-AJU3-LVEZ-BVUNM","height":629687,"version":1,"ecBlockId":"17180587905509429047","ecBlockHeight":629676},{"type":0,"subtype":0,"timestamp":152299501,"deadline":1440,"senderPublicKey":"d21c6c25feb45a73e35cebb9eab27aac204458e9bb515fbd25abd1ad4fb77618","recipient":"17826405847982443566","recipientRS":"BURST-353G-PGHH-U98T-HX2TG","amountNQT":"46342288983","feeNQT":"100000000","signature":"809b8fb9ed068f92a04f815ad25bbb3ff116ae716e0f87119c650219aaaab1013889300d19ef4c84d45771cf5ca94d628b706d09b663f40fa0f15411b84b0090","signatureHash":"8339d8684a3c53c37aa992529e8c5cfcc20ec9efe7cbd25f3ec5933db052dbab","fullHash":"eaf475f07568e5135ad0daffef299dadaa20129fbbef914198b48c3b31f00a13","transaction":"1433666912142095594","sender":"11084303456378837181","senderRS":"BURST-JQ7X-AJU3-LVEZ-BVUNM","height":629687,"version":1,"ecBlockId":"17180587905509429047","ecBlockHeight":629676},{"type":0,"subtype":0,"timestamp":152299564,"deadline":1440,"senderPublicKey":"d8bd9235e5c6371fc3dab4b5c986f03576150c9f940f5dad7842c282671bbd28","recipient":"5995410776986179782","recipientRS":"BURST-YQ88-CSQE-VUL3-7UZE8","amountNQT":"1092723460227","feeNQT":"200000000","signature":"9eebfee3c465c364d31f689e0e6525f4b24bc459cfe6e944c19cac3a808fb5039a7df341e4b97cda92d3997bee64980e7c2d1f1f7a513279e5d551ab488ff895","signatureHash":"9922aacb28cc6101a075b881a3c87dd3a563aa393cb81b940f5ea63bf1d4c644","fullHash":"1487d39d1645b1484853fc9c7dc77ea414407945c546ed6b731603a64bad7833","transaction":"5238043805048080148","sender":"13383190289605706987","senderRS":"BURST-HK9D-P74Q-XDEJ-D6PGM","height":629687,"version":1,"ecBlockId":"17180587905509429047","ecBlockHeight":629676}],"requestProcessingTime":0}
```

**Comment by llybin** [comment] 2019-06-09 22:38
Still reproduced, could you please look on this.

**Comment by harry1453** [comment] 2019-06-10 14:02
Got a 502 on your node but reproducing on others. This is probably a bug.

**Comment by harry1453** [comment] 2019-06-10 17:23
Very strange, no longer reproducible

**Comment by harry1453** [comment] 2019-06-10 18:16
This only happens for certain blocks. For example, all of the txs for block id 3599132658911212585 stayed in mempool on the CG node. Strange behaviour.

**Comment by harry1453** [comment] 2019-06-12 09:55
#167

**Comment by llybin** [comment] 2019-07-17 18:02
I see again old unconfirmed transactions 2.4.1:
https://explorer.burst.devtrue.net/

![image](https://user-images.githubusercontent.com/5445357/61399095-a0392980-a8f7-11e9-8769-c5dccb04e5f3.png)

https://explorer.burst.devtrue.net/address/9986220025452742114

![image](https://user-images.githubusercontent.com/5445357/61399139-b2b36300-a8f7-11e9-8cbb-8caade50d55f.png)

**Comment by harry1453** [comment] 2019-07-25 12:49
Do they persist for longer than a minute?

**Comment by llybin** [comment] 2019-07-26 09:48
@harry1453 yes, I notice it periodically. https://explorer.burst.devtrue.net/

![image](https://user-images.githubusercontent.com/5445357/61943192-25da6a80-afc5-11e9-8d86-b46b605dd8f0.png)

**Comment by llybin** [comment] 2019-07-26 09:54
I took the screenshot above, after 4 minutes the unconfirmed transactions were all cleared. Maybe the problem is that pools don't take them quickly? Imho there have some trouble.. Sometimes I see 0 transactions in blocks, but there have unconfirmed.

**Comment by harry1453** [comment] 2019-07-31 06:19
Okay. I will keep an eye out in case this issue becomes persistent again.

**Comment by llybin** [comment] 2020-01-05 13:48
P2P and APIv1 return different data of UnconfirmedTransactions, I still see stranges in APIv1, ctrl+f in log below: BURST-EXDK-YY59-EQS2-8QBQY

![image](https://user-images.githubusercontent.com/5445357/71781018-64586480-2ffc-11ea-92ee-860e2e9cc36c.png)

`curl "http://wallet.burst.devtrue.net:8125/burst?requestType=getUnconfirmedTransactions"`

{"unconfirmedTransactions":[{"type":2,"subtype":2,"timestamp":170448958,"deadline":1440,"senderPublicKey":"48abceeec952e3a7813d4a54d8dfdd2584bd30d70682080f5776ec44c8361318","amountNQT":"0","feeNQT":"735001","signature":"611d625085a9e481ed45b84b7552d01399c6b1b7192256fa4288c7625e8ad4039b219ddc4e7f1541bcbfee83734bbeee762a0df4cab8af99cecea074a02eab7b","signatureHash":"ba7566205dd8ecc3de8df366dc57962cb79cd96f9e095858db06318a2cd77e64","fullHash":"2e0e41383ea5f2dee0588c8976ae23c574cf2ffc72997db904661cfe32a53b6f","transaction":"16065084507434323502","attachment":{"version.AskOrderPlacement":1,"asset":"10987192031618394393","quantityQNT":"100000000","priceNQT":"2"},"sender":"8023504647877981553","senderRS":"BURST-EXDK-YY59-EQS2-8QBQY","height":704772,"version":1,"ecBlockId":"16853257685141739720","ecBlockHeight":704762},{"type":0,"subtype":0,"timestamp":170509300,"deadline":1000,"senderPublicKey":"447db598ab0b8b128516b3a70b9d87ea4cdb460fb4c550167cbfceda865fb03d","recipient":"7159002186570865347","recipientRS":"BURST-U8Q5-KW4E-RNZM-84HQ8","amountNQT":"1000000","feeNQT":"735000","signature":"f321384587c6aad27524473b3ce80b8c75ebae484ac9e808169ab491b87cab0132df4e324388245942ef04713646853aed38026256465afe9ed735cedb91060a","signatureHash":"b944096e2ab4777582db50aa1d66332a134bc629919c87efcce6de37ad942762","fullHash":"914f1ba126f601480301e145a5ab155a311b3e6cc61ac694e01e84e0c2c53dee","transaction":"5188698891479633809","sender":"16649368274173126122","senderRS":"BURST-YTHC-9GUD-RUMB-GJM5G","height":705021,"version":1,"ecBlockId":"12535944268672714890","ecBlockHeight":705012},{"type":0,"subtype":0,"timestamp":170509164,"deadline":1440,"senderPublicKey":"b79c4afd0a73410c34813b225d1244ea88fe869d9aef1b23cc648d1fff2dd95d","recipient":"16175030181959184549","recipientRS":"BURST-EE77-A3KG-KRZK-G2CY2","amountNQT":"700000000","feeNQT":"2205000","signature":"7491bb5edf48508881ed21b6d0eac3512361d13e4f45802310ed0af1d2fd4507a54e3fc835950ea16a1196e6565027c7dc39cafbf229d9fc16392ed06e7de617","signatureHash":"78a3a740f02c7423918957847f046f8dc43d1785d666f9a96f58dafe82dbaadb","fullHash":"28def32aa8109452236617360578b0b38b5c9ff858b6cbb65cfffb4996dbb9e1","transaction":"5950399322124443176","attachment":{"version.PublicKeyAnnouncement":1,"recipientPublicKey":"6c55bff30124a15a47e06bfa90086b4467a86516f78cd9a6191ee7209defb059"},"sender":"15759722322633634763","senderRS":"BURST-YEYD-YJRP-UGDR-F9GFP","height":705021,"version":1,"ecBlockId":"12535944268672714890","ecBlockHeight":705012},{"type":0,"subtype":0,"timestamp":170509173,"deadline":1440,"senderPublicKey":"36c5624d36bd9361bd72af0f26fa800bebc7900739ac5f4b26c585edec55a22f","recipient":"3269116517526226634","recipientRS":"BURST-8KQC-6VUA-SRB6-4WKRU","amountNQT":"100000000","feeNQT":"2940000","signature":"340c0157da4cc266c32239a878fab6fb0bf7e2c38143564266d41db216cc3e0200866b5b2020613d0ce847d454c270cc8bf07f3c177a5c92df860540a135b196","signatureHash":"624d637dcc4e89c5d0e5325ddbe27882aa15685e501216176c53f74a83ac9360","fullHash":"df2fdb5704efea57e83566810cf4c660cba5d4e4791ef414f551b2d2094690e5","transaction":"6335138627782914015","attachment":{"version.PublicKeyAnnouncement":1,"recipientPublicKey":"6f175c1699c58e3ecfd69486994b763cf9e275e6df53271c2cac8dade2d4c27a"},"sender":"17645868983613622747","senderRS":"BURST-Z4GV-D76P-R8NJ-HSPSB","height":705021,"version":1,"ecBlockId":"12535944268672714890","ecBlockHeight":705012},{"type":0,"subtype":0,"timestamp":170509265,"deadline":1440,"senderPublicKey":"954e0cf358d120998cca2923e1a5fd761547371d83b7c3846d85858b26de282e","recipient":"13383190289605706987","recipientRS":"BURST-HK9D-P74Q-XDEJ-D6PGM","amountNQT":"10000000000","feeNQT":"5880000","signature":"b8cf36fa3aee00982b471c3602872a73a4845d5df508a6735d3d49e0f0e6d00bc2d921d6ce5012f13430836858b7b2f2af3ac1fc0a0b3ac8ffcc8c87b3c9b025","signatureHash":"d1ac60679b51cb44e2c535bd8009d526b3bcf007f8e94854ea9a4f4234315704","fullHash":"2e425d0cace3815d30d36ac35b7952dd97e5d3aaee3ddf641cf3d3680ad0c4bc","transaction":"6737916845604291118","attachment":{"version.Message":1,"message":"370a9df5b8874420b50e25f616d18f348a14d66ba97b49748be1e1efb08fac01","messageIsText":true},"sender":"8884607705348232020","senderRS":"BURST-PNUN-NCLZ-4GXQ-9R5MQ","height":705021,"version":1,"ecBlockId":"12535944268672714890","ecBlockHeight":705012},{"type":0,"subtype":0,"timestamp":170509156,"deadline":1440,"senderPublicKey":"d21c6c25feb45a73e35cebb9eab27aac204458e9bb515fbd25abd1ad4fb77618","recipient":"67744632438724196","recipientRS":"BURST-87M6-EBHZ-23VJ-2F7W3","amountNQT":"35259721200","feeNQT":"10000000","signature":"f850e3288bd461cd80b30611f1455aaa9ffb5068024fb6c05ac83707544a7b0ac927aa3d50bcfa9d98295b2706587224f50e4c25152fafbd2ec02ed2c5afdeb8","signatureHash":"8d3929b52c18797195827058f20ccce4fe929f968db1275117b185d9d7f334b7","fullHash":"895590b52cd0ddfa26e59cf3120cfd25489b4c1c919249c85328624d775b2ec2","transaction":"18076833369778312585","sender":"11084303456378837181","senderRS":"BURST-JQ7X-AJU3-LVEZ-BVUNM","height":705020,"version":1,"ecBlockId":"12535944268672714890","ecBlockHeight":705012}],"requestProcessingTime":0}


`curl -X POST "http://wallet.burst.devtrue.net:8123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getUnconfirmedTransactions"}'`

{"unconfirmedTransactions":[{"type":0,"subtype":0,"timestamp":170509265,"deadline":1440,"senderPublicKey":"954e0cf358d120998cca2923e1a5fd761547371d83b7c3846d85858b26de282e","recipient":"13383190289605706987","amountNQT":10000000000,"feeNQT":5880000,"ecBlockHeight":705012,"ecBlockId":"12535944268672714890","signature":"b8cf36fa3aee00982b471c3602872a73a4845d5df508a6735d3d49e0f0e6d00bc2d921d6ce5012f13430836858b7b2f2af3ac1fc0a0b3ac8ffcc8c87b3c9b025","attachment":{"version.Message":1,"message":"370a9df5b8874420b50e25f616d18f348a14d66ba97b49748be1e1efb08fac01","messageIsText":true},"version":1},{"type":0,"subtype":0,"timestamp":170509300,"deadline":1000,"senderPublicKey":"447db598ab0b8b128516b3a70b9d87ea4cdb460fb4c550167cbfceda865fb03d","recipient":"7159002186570865347","amountNQT":1000000,"feeNQT":735000,"ecBlockHeight":705012,"ecBlockId":"12535944268672714890","signature":"f321384587c6aad27524473b3ce80b8c75ebae484ac9e808169ab491b87cab0132df4e324388245942ef04713646853aed38026256465afe9ed735cedb91060a","attachment":{},"version":1},{"type":0,"subtype":0,"timestamp":170509173,"deadline":1440,"senderPublicKey":"36c5624d36bd9361bd72af0f26fa800bebc7900739ac5f4b26c585edec55a22f","recipient":"3269116517526226634","amountNQT":100000000,"feeNQT":2940000,"ecBlockHeight":705012,"ecBlockId":"12535944268672714890","signature":"340c0157da4cc266c32239a878fab6fb0bf7e2c38143564266d41db216cc3e0200866b5b2020613d0ce847d454c270cc8bf07f3c177a5c92df860540a135b196","attachment":{"version.PublicKeyAnnouncement":1,"recipientPublicKey":"6f175c1699c58e3ecfd69486994b763cf9e275e6df53271c2cac8dade2d4c27a"},"version":1},{"type":0,"subtype":0,"timestamp":170509164,"deadline":1440,"senderPublicKey":"b79c4afd0a73410c34813b225d1244ea88fe869d9aef1b23cc648d1fff2dd95d","recipient":"16175030181959184549","amountNQT":700000000,"feeNQT":2205000,"ecBlockHeight":705012,"ecBlockId":"12535944268672714890","signature":"7491bb5edf48508881ed21b6d0eac3512361d13e4f45802310ed0af1d2fd4507a54e3fc835950ea16a1196e6565027c7dc39cafbf229d9fc16392ed06e7de617","attachment":{"version.PublicKeyAnnouncement":1,"recipientPublicKey":"6c55bff30124a15a47e06bfa90086b4467a86516f78cd9a6191ee7209defb059"},"version":1},{"type":0,"subtype":0,"timestamp":170509156,"deadline":1440,"senderPublicKey":"d21c6c25feb45a73e35cebb9eab27aac204458e9bb515fbd25abd1ad4fb77618","recipient":"67744632438724196","amountNQT":35259721200,"feeNQT":10000000,"ecBlockHeight":705012,"ecBlockId":"12535944268672714890","signature":"f850e3288bd461cd80b30611f1455aaa9ffb5068024fb6c05ac83707544a7b0ac927aa3d50bcfa9d98295b2706587224f50e4c25152fafbd2ec02ed2c5afdeb8","attachment":{},"version":1}]}

**Comment by llybin** [comment] 2020-01-05 13:52
Probably it's duplicate of this applied transaction: https://explorer.burst.devtrue.net/tx/11621113865088862204

**Comment by llybin** [comment] 2020-01-09 11:05
![image](https://user-images.githubusercontent.com/5445357/72062521-89095080-330a-11ea-8aa7-3cc0a803e367.png)

https://explorer.burst.devtrue.net/address/10268544688875950721

![image](https://user-images.githubusercontent.com/5445357/72062540-93c3e580-330a-11ea-852c-dcf024469e11.png)

**Comment by shefass** [comment] 2020-01-09 11:30
I found source of it. I informed him about this behaviour. It is
probably: "edge case if you just sold an asset and posted a ask order
just before".
It is related to new CurbShifs chat app.


2020-01-09, kt, 13:05 Lev Lybin <notifications@github.com> rašė:

**Comment by llybin** [comment] 2020-01-09 15:22
Cool, but need fix this case(s) on node also.

**Comment by llybin** [comment] 2020-01-09 15:25
> @harry1453 yes, I notice it periodically. https://explorer.burst.devtrue.net/
> 
> ![image](https://user-images.githubusercontent.com/5445357/61943192-25da6a80-afc5-11e9-8d86-b46b605dd8f0.png)

@shefass explained me slot system, this case ok. I rechecked my messages, I see troubles only with assets. And different data unconfirmed transaction between apiv1 and p2p api

**Comment by llybin** [comment] 2020-02-26 11:39
Could you reopen this issue?

**Comment by harry1453** [comment] 2020-02-27 13:30
Sure. We need to come up with a reproducible scenario that causes this..

**Comment by llybin** [comment] 2020-02-27 13:57
@harry1453 ask @shefass as far as I understood it was caused by Hotwallet, if we will know what he fixed-  will know how to reproduce :)

here two cases. 

1. duplicates transactions
2. diffrent data
 curl "http://wallet.burst.devtrue.net:8125/burst?requestType=getUnconfirmedTransactions"
and
curl -X POST "http://wallet.burst.devtrue.net:8123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getUnconfirmedTransactions"}'

**Comment by harry1453** [comment] 2020-02-27 19:30
2 is caused by peer fingerprint marking

**Comment by llybin** [comment] 2020-02-27 19:48
sorry, there may be a misunderstanding, I mean about this: https://github.com/burst-apps-team/burstcoin/issues/166#issuecomment-570914076
I've seen a buggy unconfirmed transaction only in API, P2P was ok. Looks like they have different sources...

**Comment by harry1453** [comment] 2020-02-29 12:50
Oh, that's strange... I will look into it, the JSON encoding is different for the 2..

**Comment by damccull** [comment] 2021-05-20 02:28
It appears that the UnconfirmedTransactionStoreImpl class maintains a mapping of peers that have a transaction already. I assume this is so that the peers are not constantly broadcasting the same transactions to the same peers. Looks like if peer A knows that peer B already has transaction X, then transaction X will not be included in the p2p response.

Conversely, the public API returns ALL unconfirmed transactions that peer A knows about each time its called.

The behavior difference is likely due to the purposes behind each API. The p2p API needs to minimize traffic and also needs to avoid a transaction loop where peers are sending each other the same transactions over and over. On the other hand, a user client will always want to see all the unconfirmed transactions available.

With this information, I do not believe the difference in unconfirmed transactions between the two APIs is the reason this problem exists.

**Comment by ohager** [comment] 2021-05-24 20:59
high-prio issue since 2019 - @jjos2372 - How to treat this issue?

**Comment by jjos2372** [comment] 2021-06-03 17:49
Closing this for now @ohager , we had some other invalid transactions not leaving the unconfirmed list and they were fixed. Very good analysis by @damccull about the differences between the p2p and public api.

**Closed by jjos2372** 2021-06-03 17:49 UTC
Labels: backend, bug, codebase, priority-high
